syntax = "proto3";

option objc_class_prefix = "PROTO";

import "base/result.proto";

package com.mineplanet.pojo.health;

option java_outer_classname = "HealthProto";
option go_package = "github.com/jimiechen/mineplanet/protocols/generated/go/proto/base";

// 服务健康检查请求
message ServiceHealthCheckRequest {
  enum Type {
    none = 0;
    max = 2100;
    min = 2097;
  }

  string service_name = 1;
}

// 服务健康检查响应
message ServiceHealthCheckResponse {
  enum Type {
    none = 0;
    max = 2100;
    min = 2098;
  }

  com.mineplanet.pojo.pb.Result result = 1;
  string status = 2;      // "OK", "Unhealthy"
  int64 timestamp = 3;
}
